apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Interconnect
metadata:
  name: dc2-router
spec:
  deploymentPlan:
    size: 1
    role: interior
    placement: Any
  interRouterListeners:
    # accept connections from other routers
    - port: 55672
      expose: true
      authenticatePeer: false
      saslMechanisms: ANONYMOUS
  listeners:
    # internal clients connect here
    - port: 5672
    # external clients connect here
    - port: 5671
      sslProfile: default
      expose: true
    # exposing web console
    - port: 8080
      authenticatePeer: true
      expose: true
      http: true
  interRouterConnectors:
    # connection to gateway router
    - host: dc1-gateway.dc1.svc.cluster.local
      port: 55672
      saslMechanisms: ANONYMOUS
  connectors:
    # connection to local broker
    - host: dc2-broker-amqp-0-svc.dc2.svc.cluster.local
      port: 5672
      name: dc2-broker
      routeContainer: true
  addresses:
    # routing b2b messages through broker
    - prefix: b2b
      waypoint: true
  # always single producer and consumer regardless of num. of clients
  autoLinks:
    # direct messages from producers to the broker on this address
    - address: b2b.dc2.incoming
      connection: dc2-broker
      direction: out
      # 0 from prod to out-al, 1 from in-al to cons
      phase: 0
    # pulls messages from the broker into the router and onto consumers
    - address: b2b.dc2.outgoing
      connection: dc2-broker
      direction: in
      phase: 1
