apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemis
metadata:
  name: dc1-broker
spec:
  adminUser: admin
  adminPassword: admin
  deploymentPlan:
    size: 1
    image: registry.redhat.io/amq7/amq-broker:7.7
    requireLogin: false
    persistenceEnabled: true
    messageMigration: true
    journalType: nio
  console:
    expose: true
  acceptors:
    - name: amqp
      protocols: amqp
      port: 5672
      sslEnabled: false
      expose: true
